'use strict';
var path=require('path');

module.export=function(config){
    if(process.env.RELEASE){
        config.singleRun = true;
    }
    config.set({
        basePath:'../',
        frameworks:['mocha','chai'],
        files:[
        {pattern:'test/index.js',included:true,watch:false}],
        exclude:['node_modules/'],
        preprocessors:{
            'test/index.js':['webpack','sourcemap'],
        },
        webpack:{
            devtool:'inline-source-map',
            module:{
                noParse:[
                /node_modules\/sinon//,
                ],
                loaders:[{
                    test:/\.js$/,
                    include:[
                    /src|test|recharts/,
                    ],
                    exclude:/node_modules/,
                    loader:'babel',
                },{
                    test:/\.json$/,
                    loader:'json',
                }],
                postLoaders:[{
                    test:/\.js$/,
                    include:/src/,
                    exclude:/node_modules/,
                    loader:'istanbul-instrumenter',
                }],
            },
            externals:{
                'jsdom':'window',
                'react/lib/ExectionEnvironment':true,
                'react/lib/ReactContext':'window',
                'text-encoding':'window',
            },
            resolve:{
                alias:{
                    'sinon':'sinon/pkg/sinon',
                    'recharts':path.resolve('./src/index.js'),
                },
            },
            stats:{
                assets:false,
                colors:true,
                version:false,
                hash:false,
                timings:false,
                chunks:false,
                chunkModules:false,
            },
            debug:false,
        },
        plugins:[
            'karma-webpack',
            'karma-mocha',
            'karma-coverage',
            'karma-chai',
            'karma-sourcemap-loader',
            'karma-chrome-launcher',
            'istanbul-instrumenter-loader',
            'karma-coveralls',
        ],
        reporters:['progress','coverage','coveralls'],
        coverageReporter:{
            dir:'test',
            reporters:[{
                type:'html',
                subdir:'coverage',
            },{
                type:'text',
            },{
                type:'lcov',
                subdir:'coverage',
            }]
        },
        webpackMiddleware:{
            noInfo:true,
        },
        port:9876,
        colors:true,
        logLevel:config.LOG_INFO,
        browsers:['Chrome'],
        browserNoActivityTimeout:60000,
    });
};