export default {
	firstPage:{
		firstPageNumInit:'http://localhost:3000/hour/init',
		fetch:'http://localhost:3000/hour/change'
	},
	sellers:{
		sellersListInit:'http://localhost:3003',
		allSellersLineChartInit:'http://localhost:3003/allsellers/',
		allSellersTableInit:'http://localhost:3003/allsellers/allSellersTableInit',
		singleSellerLineChartInit:'http://localhost:3000/hour/singleSeller/',
		singleSellerCustomerNumInit:'http://localhost:3000/hour/singleSellerCustomerNumInit/',
		singleSellerCustomerNumFetch:'http://localhost:3000/hour/singleSellerCustomerNumFetch/',
		singleSellerCustomerFlowInit:'http://localhost:3000/hour/singleSellerCustomerFlowInit/',
		singleSellerRadar:'http://localhost:3000/hour/singleSellerRadar/',
		singleSellerStayBar:'http://localhost:3000/hour/singleSellerStayBar/',
		singleSellerOldOrNew:'http://localhost:3000/hour/singleSellerOldOrNew/',
		singleSellerTimeSection:'http://localhost:3000/hour/singleSellerTimeSection/',
		singleSellerDeepVisit:'http://localhost:3000/hour/singleSellerDeepVisit/',
		singleSellerCycleAndActive:'http://localhost:3000/hour/singleSellerCycleAndActive/'
	}
}