export default {
	firstPage:{
		numInit:'firstPageNumInit',
		fetch:'firstPageFetch',
		sellersInit:'firstPageSellers'
	},
	sellers:{
		sellersListInit:'sellersListInit',
		allSellersLineChartInit:'allSellersLineChartInit',
		// allSellersTableInit:'allSellersTableInit',
		singleSellerLineChartInit:'singleSellerLineChartInit',
		singleSellerCustomerNumInit:'singleSellerCustomerNumInit',
		singleSellerCustomerNumFetch:'singleSellerCustomerNumFetch',
		singleSellerCustomerInInit:'singleSellerCustomerInInit',
		singleSellerCustomerFlowInit:'singleSellerCustomerFlowInit',
		singleSellerRadar:'singleSellerRadar',
		singleSellerStayBar:'singleSellerStayBar',
		singleSellerOldOrNew:'singleSellerOldOrNew',
		singleSellerTimeSection:'singleSellerTimeSection',
		singleSellerDeepVisit:'singleSellerDeepVisit',
		// singleSellerCycleAndActive:'singleSellerCycleAndActive',
		singleSellerCycleInit:'singleSellerCycleInit',
		singleSellerActiveInit:'singleSellerActiveInit'
	},
	statistics:{
		statisticsCustomerNumInit:'statisticsCustomerNumInit',
		statisticsOldOrNewInit:'statisticsOldOrNewInit',
		statisticsTimeSectionInit:'statisticsTimeSectionInit',
		statisticsCycleInit:'statisticsCycleInit',
		statisticsActiveInit:'statisticsActiveInit'
	},
	compare:{
		numInit:'compareCustomerNum',
		cycleInit:'compareCustomerCycle',
		activeInit:'compareCustomerActive',
		oldOrNewInit:'compareCustomerOldOrNew',
		deepVisitInit:'compareCustomerDeepVisit',
		outInit:'compareCustomerOutInit',
		sellersNumInit:'compareSellersNum',
		sellersListInit:'compareSellersList',
		sellersInInit:'compareSellersIn',
		sellersOldOrNewInit:'compareSellersOldOrNew',
		sellersOutInit:'compareSellersOut',
		sellersDeepInit:'compareSellersDeep',
		sellersStayInit:'compareSellersStay',
		sellersActiveInit:'compareSellersActive',
		sellersTimeSectionInit:'compareSellersTimeSection',
		sellersCycleInit:'compareSellersCycle'
	}
}